const c=document.querySelector('#c'),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
const saved=JSON.parse(localStorage.getItem('erosbound-save')||'{}');
let me={x:saved.x||550,y:saved.y||390,name:saved.name||'Adventurer',hp:100},keys={},gold=saved.gold??25,xp=saved.xp??0,hasKey=!!saved.hasKey;
const npc={x:600,y:235,name:'Elira'};
const travelers=[{x:320,y:430,name:'Luna',dx:1.0,dy:.45},{x:850,y:470,name:'Kael',dx:-.7,dy:.8},{x:920,y:330,name:'Mira',dx:-.9,dy:-.4}];
function save(){localStorage.setItem('erosbound-save',JSON.stringify({x:me.x,y:me.y,name:me.name,gold,xp,hasKey}))}
function tile(){ctx.fillStyle='#315b3c';ctx.fillRect(0,0,1200,700);for(let i=0;i<1200;i+=40)for(let j=0;j<700;j+=40){ctx.fillStyle=(i/40+j/40)%2?'#365f40':'#315b3c';ctx.fillRect(i,j,40,40)}ctx.fillStyle='#7c5838';ctx.fillRect(450,100,300,210);ctx.fillStyle='#3c2630';ctx.fillRect(475,125,250,160);ctx.fillStyle='#c89b62';ctx.fillRect(575,255,50,55);ctx.fillStyle='#2a492f';for(let i=0;i<10;i++)ctx.fillRect(50+i*115,540+(i%2)*45,35,70)}
function person(p,color){ctx.fillStyle='#0008';ctx.fillRect(p.x-12,p.y+14,24,8);ctx.fillStyle=color;ctx.fillRect(p.x-12,p.y-12,24,28);ctx.fillStyle='#f3d2b6';ctx.fillRect(p.x-8,p.y-25,16,14);ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText(p.name,p.x,p.y-32)}
function draw(){tile();person(npc,'#bd5e9e');travelers.forEach(p=>person(p,'#ffd36e'));person(me,'#72d5ff');requestAnimationFrame(draw)}draw();
setInterval(()=>{let sp=4;if(keys.w||keys.ArrowUp)me.y-=sp;if(keys.s||keys.ArrowDown)me.y+=sp;if(keys.a||keys.ArrowLeft)me.x-=sp;if(keys.d||keys.ArrowRight)me.x+=sp;me.x=Math.max(25,Math.min(1175,me.x));me.y=Math.max(25,Math.min(675,me.y));travelers.forEach(p=>{p.x+=p.dx;p.y+=p.dy;if(p.x<50||p.x>1150)p.dx*=-1;if(p.y<330||p.y>650)p.dy*=-1});let d=Math.hypot(me.x-npc.x,me.y-npc.y),pr=document.querySelector('#prompt');pr.style.display=d<90?'block':'none';pr.textContent=d<90?'Elira: choose Negotiate, Romance, or Duel below':'';save()},50);
onkeydown=e=>{if(document.activeElement.tagName!=='INPUT')keys[e.key]=true};onkeyup=e=>keys[e.key]=false;
function log(t,cl=''){let d=document.createElement('div');d.className=cl;d.textContent=t;document.querySelector('#chatlog').append(d);d.scrollIntoView()}
document.querySelector('#name').value=me.name;document.querySelector('#rename').onclick=()=>{me.name=document.querySelector('#name').value.trim().slice(0,18)||'Adventurer';save();log('Name changed to '+me.name+'.','sys')};
function send(){let i=document.querySelector('#chat'),v=i.value.trim();if(v){log(me.name+': '+v);i.value=''}}document.querySelector('#send').onclick=send;document.querySelector('#chat').onkeydown=e=>{if(e.key==='Enter')send()};
document.querySelectorAll('#actions button').forEach(b=>b.onclick=()=>{if(Math.hypot(me.x-npc.x,me.y-npc.y)>110)return log('Move closer to Elira first.','sys');if(hasKey)return log('Elira: You already have the dungeon key.','sys');let a=b.dataset.a;if(a==='talk')log('You help Elira settle a supply dispute. She rewards your diplomacy with the dungeon key. +50 XP','sys');if(a==='romance')log('After mutual flirting, the scene fades to black. Elira gives you the dungeon key. +50 XP','sys');if(a==='fight')log('Elira accepts a friendly duel. After the sparring match, she awards you the dungeon key. +50 XP','sys');hasKey=true;xp+=50;gold+=10;document.querySelector('#xp').textContent=xp;document.querySelector('#gold').textContent=gold;document.querySelector('#dialog').innerHTML='<b>Quest complete:</b> Dungeon key acquired. All three interaction routes lead to positive progression.';save()});
document.querySelector('#xp').textContent=xp;document.querySelector('#gold').textContent=gold;if(hasKey)document.querySelector('#dialog').innerHTML='<b>Quest complete:</b> Dungeon key acquired. Progress is saved in this browser.';
log('GitHub Pages build: static mode. The yellow travelers are simulated. Real multiplayer requires a separate WebSocket backend.','sys');
